### ISSUE TITLE
Features exist

### ISSUE THREAD

**Issue by ManindraDeMel** [aryanVanaik/gym-tracker-app#1]
I was wondering if you were creating this to practice your full-stack skills. Otherwise there are several fitness apps available that offer the features you're looking for, including calorie tracking, workout tracking, and workout creation based on personal goals:

MyFitnessPal: This app is known for its extensive food and activity database, making it easy to log food intake and physical activities. It allows for customization based on your health goals and includes a database of over 14 million foods. However, it does not provide training services and some tracking services may be confusing or inaccurate. MyFitnessPal integrates with more than 50 other apps and devices, offering a library of 50 workout routines​​.

Strong - Workout Tracker & Gym Log: Strong is a versatile app suitable for users of all experience levels. It offers features like supersets, custom exercises, and workout scheduling. The app is available on iPhone, Android, and Apple Watch, allowing you to access your training from any device. Strong is praised for its user-friendliness and comprehensive feature set​​.

Coachify AI: Workout Planner: This app utilizes AI to generate workout schedules and nutrition goals based on your information like height, weight, and fitness goals. It includes a convenient calorie counter system and provides different workout options. Coachify AI also offers 24/7 AI assistance for workout and diet planning and is suitable for both beginners and experienced users​​.

Each of these apps has its unique strengths and caters to different needs, whether it's comprehensive food tracking, detailed workout logging, or AI-driven workout and nutrition planning. You can choose the one that best aligns with your specific fitness goals and preferences.

**Comment by aryanVanaik** [comment]
Thanks for the advice, tbh This app was a bit of both as I did want a fitness app but I also wanna practice my full-stack skills so I decided might aswell make one but probably more towards practicing my full-stack skills
